[metadata]

date = "12/7/2023"
# december 7th 2009

material_notes = "It's just PLA mates"

[settings]

material_print_temperature = 218
material_bed_temperature = 50
material_bed_temperature_layer_0 = 60