[metadata]

date = "1/1/2023"

[settings]

machine_depth                                    = 220
machine_end_gcode                                = """
M140 S0 ;Turn-off bed
M106 S0 ;Turn-off fan
M104 S0 ;Turn-off hotend
G91 ;Relative positioning
G1 E-2 F2700 ;Retract a bit
G1 E-2 Z0.2 F2400 ;Retract and raise Z
G1 X5 Y5 F3000 ;Wipe out
G1 Z10 ;Raise Z more
G90 ;Absolute positionning
M300 S440 P500 ; plays a tone at 440 Hz for 250 ms
G1 X0 Y{machine_depth} ;Present print
M84 X Y E ;Disable all steppers but Z
"""
machine_start_gcode                              = """
G92 E0 ; Reset Extruder
M140 S{material_bed_temperature_layer_0} ; Set Heat Bed temperature
M104 S{material_print_temperature_layer_0} ; Set Extruder temperature
G28 ; Home all axes
M109 S{material_print_temperature_layer_0} ; Wait for Extruder temperature
M190 S{material_bed_temperature_layer_0} ; Wait for Heat Bed temperature
G29 ; Auto bed-level (BL-Touch)
M500 ; Used to store G29 results in memory
G92 E0 ; Reset Extruder
G1 Z1.0 F3000 ; move z up little to prevent scratching of surface
G1 X0.1 Y20 Z0.3 F5000.0 ; move to start-line position
G1 X0.1 Y200.0 Z0.3 F1500.0 E15 ; draw 1st line
G1 X0.4 Y200.0 Z0.3 F5000.0 ; move to side a little
G1 X0.4 Y20 Z0.3 F1500.0 E30 ; draw 2nd line
G92 E0 ; reset extruder
G1 Z1.0 F3000 ; move z up little to prevent scratching of surface
"""
machine_heated_bed                               = true
machine_height                                   = 250
machine_width                                    = 220
