[general]
name = "TAZ Workhorse Aero 0.5mm"

[settings]
acceleration_print         = 500
acceleration_travel        = 500
jerk_print                 = 12
jerk_travel                = 12
machine_acceleration       = 500
machine_depth              = 282
machine_heated_bed         = true
machine_height             = 286
machine_max_acceleration_e = 1000
machine_max_acceleration_x = 9000
machine_max_acceleration_y = 9000
machine_max_acceleration_z = 9000
machine_max_feedrate_e     = 40
machine_max_feedrate_x     = 800
machine_max_feedrate_y     = 800
machine_max_feedrate_z     = 3
machine_nozzle_size        = 0.5
machine_probe_type         = "nozzle"
machine_width              = 282

machine_start_gcode = """
;This G-Code has been generated specifically for the LulzBot TAZ Workhorse with an 0.5mm Aero Tool Head
M73 P0                                            ; clear GLCD progress bar
M75                                               ; start GLCD timer
G26                                               ; clear potential 'probe fail' condition
M107                                              ; disable fans
M420 S0                                           ; disable previous leveling matrix
G90                                               ; absolute positioning
M82                                               ; set extruder to absolute mode
G92 E0                                            ; set extruder position to 0
M140 S{material_bed_temperature_layer_0}          ; start bed heating up
M109 R{material_soften_temperature}               ; soften filament before homing Z
G28                                               ; Home all axis
G1 E-30 F100                                      ; retract filament
M109 R{material_wipe_temperature}                 ; wait for extruder to reach wiping temp
G1 X-15 Y100 F3000                                ; move above wiper pad
G1 Z1                                             ; push nozzle into wiper
G1 X-17 Y95 F1000                                 ; slow wipe
G1 X-17 Y90 F1000                                 ; slow wipe
G1 X-17 Y85 F1000                                 ; slow wipe
G1 X-15 Y90 F1000                                 ; slow wipe
G1 X-17 Y80 F1000                                 ; slow wipe
G1 X-15 Y95 F1000                                 ; slow wipe
G1 X-17 Y75 F2000                                 ; fast wipe
G1 X-15 Y65 F2000                                 ; fast wipe
G1 X-17 Y70 F2000                                 ; fast wipe
G1 X-15 Y60 F2000                                 ; fast wipe
G1 X-17 Y55 F2000                                 ; fast wipe
G1 X-15 Y50 F2000                                 ; fast wipe
G1 X-17 Y40 F2000                                 ; fast wipe
G1 X-15 Y45 F2000                                 ; fast wipe
G1 X-17 Y35 F2000                                 ; fast wipe
G1 X-15 Y40 F2000                                 ; fast wipe
G1 X-17 Y70 F2000                                 ; fast wipe
G1 X-15 Y30 Z2 F2000                              ; fast wipe
G1 X-17 Y35 F2000                                 ; fast wipe
G1 X-15 Y25 F2000                                 ; fast wipe
G1 X-17 Y30 F2000                                 ; fast wipe
G1 X-15 Y25 Z1.5 F1000                            ; slow wipe
G1 X-17 Y23 F1000                                 ; slow wipe
G1 Z10                                            ; raise extruder
M109 R{material_probe_temperature}                ; wait for extruder to reach probe temp
G1 X-9 Y-9                                        ; move above first probe point
M204 S100                                         ; set probing acceleration
G29                                               ; start auto-leveling sequence
M420 S1                                           ; activate bed level matrix
M425 Z                                            ; use measured Z backlash for compensation
M425 Z F0                                         ; turn off measured Z backlash compensation. (if activated in the quality settings, this command will automatically be ignored)
M204 S500                                         ; restore standard acceleration
G1 X0 Y0 Z15 F5000                                ; move up off last probe point
G4 S1                                             ; pause
M400                                              ; wait for moves to finish
M117 Heating...                                   ; progress indicator message on LCD
M109 R{material_print_temperature_layer_0}        ; wait for extruder to reach printing temp
M190 R{material_bed_temperature_layer_0}          ; wait for bed to reach printing temp
G1 Z2 E0 F75                                      ; prime tiny bit of filament into the nozzle
M117 TAZ Workhorse Printing...                    ; progress indicator message on LCD
"""

machine_end_gcode = """
M400                                              ; wait for moves to finish
M140 S{material_part_removal_temperature}         ; start bed cooling
M104 S0                                           ; disable hotend
M107                                              ; disable fans
G91                                               ; relative positioning
G1 E-1 F300                                       ; filament retraction to release pressure
G1 Z20 E-5 X-20 Y-20 F3000                        ; lift up and retract even more filament
G1 E6                                             ; re-prime extruder
M117 Cooling please wait                          ; progress indicator message on LCD
G90                                               ; absolute positioning
G1 Y0 F3000                                       ; move to cooling position
M190 R{material_part_removal_temperature}         ; wait for bed to cool down to removal temp
G1 Y280 F3000                                     ; present finished print
M140 S{material_keep_part_removal_temperature_t}  ; keep temperature or cool downs
M77                                               ; stop GLCD timer
M84                                               ; disable steppers
G90                                               ; absolute positioning
M117 Print Complete.                              ; print complete message
"""