[settings]

acceleration_enabled                                 = true
acceleration_infill                                 = 700
acceleration_ironing                                 = 700
acceleration_layer_0                                 = 700
acceleration_prime_tower                                 = 700
acceleration_print                                 = 700
acceleration_print_layer_0                                 = 700
acceleration_roofing                                 = 700
acceleration_skirt_brim                                 = 700
acceleration_support                                 = 700
acceleration_support_bottom                                 = 700
acceleration_support_infill                                 = 700
acceleration_support_interface                                 = 700
acceleration_support_roof                                 = 700
acceleration_topbottom                                 = 700
acceleration_travel                                 = 700
acceleration_travel_layer_0                                 = 700
acceleration_wall                                 = 700
acceleration_wall_0                                 = 700
acceleration_wall_x                                 = 700
adhesion_type                                 = "skirt"
connect_infill_polygons                                 = true
connect_skin_polygons                                 = true
cool_fan_full_at_height                                 = 0.5
infill_before_walls                                 = false
infill_enable_travel_optimization                                 = true
infill_pattern                                 = "cubicsubdiv"
infill_randomize_start_location                                 = true
infill_support_angle                                 = 60
initial_bottom_layers                                 = 2
ironing_inset                                 = 0.25
ironing_line_spacing                                 = 0.4
jerk_enabled                                 = true
jerk_infill                                 = 45
jerk_ironing                                 = 45
jerk_layer_0                                 = 45
jerk_prime_tower                                 = 45
jerk_print                                 = 45
jerk_print_layer_0                                 = 45
jerk_roofing                                 = 45
jerk_skirt_brim                                 = 45
jerk_support                                 = 45
jerk_support_bottom                                 = 45
jerk_support_infill                                 = 45
jerk_support_interface                                 = 45
jerk_support_roof                                 = 45
jerk_topbottom                                 = 45
jerk_travel                                 = 45
jerk_travel_layer_0                                 = 45
jerk_wall                                 = 45
jerk_wall_0                                 = 45
jerk_wall_x                                 = 45
layer_0_z_overlap                                 = 0
layer_height                                 = 0.25
layer_height_0	                                 = 0.25
limit_support_retractions                                 = false
material_bed_temperature                                 = 65
material_bed_temperature_layer_0                                 = 70
material_crystallinity                                 = true
material_final_print_temperature                                 = 200
material_initial_print_temperature                                 = 195
material_part_removal_temperature                                 = 45
material_print_temperature                                 = 200
material_print_temperature_layer_0                                 = 195
retract_at_layer_change                                 = true
retraction_amount                                 = 1.5
retraction_count_max                                 = 45
retraction_min_travel                                 = 1
retraction_prime_speed	                                 = 15
retraction_retract_speed                                 = 15
retraction_speed                                 = 15
skirt_brim_speed                                 = 15
skirt_gap                                 = 5
skirt_line_count                                 = 3
speed_infill                                 = 40
speed_ironing                                 = 25
speed_layer_0                                 = 15
speed_prime_tower                                 = 40
speed_print                                 = 40
speed_print_layer_0                                 = 15
speed_roofing                                 = 40
speed_slowdown_layers                                 = 3
speed_support                                 = 40
speed_support_bottom                                 = 40
speed_support_infill                                 = 40
speed_support_interface                                 = 40
speed_support_roof                                 = 40
speed_topbottom                                 = 40
speed_travel                                 = 150
speed_travel_layer_0                                 = 50
speed_wall                                 = 40
speed_wall_0                                 = 40
speed_wall_x                                 = 40
top_bottom_thickness                                 = 1
travel_retract_before_outer_wall                                 = true
z_seam_x                                 = 141
z_seam_y                                 = 141