[settings]

adhesion_type                                    = "skirt"
bottom_skin_expand_distance                      = 0                     # mm
bottom_skin_preshrink                            = 0                     # mm
brim_width                                       = 5                     # mm
coasting_min_volume                              = 1                     # mm³
coasting_volume                                  = 0.050                 # mm³
connect_infill_polygons                          = true
connect_skin_polygons                            = true
cool_fan_full_at_height                          = 0.5                   # mm
cool_fan_full_layer                              = 2
expand_skins_expand_distance                     = 0                     # mm
infill_before_walls                              = false
infill_enable_travel_optimization                = true
infill_pattern                                   = "cubicsubdiv"
infill_randomize_start_location                  = true
infill_support_angle                             = 60                    # °
ironing_line_spacing                             = 0.40                  # mm
layer_height                                     = 0.25                  # mm
layer_height_0                                   = 0.25                  # mm
limit_support_retractions                        = false
material_bed_temperature                         = 65                    # °C
material_break_temperature                       = 170                   # °C
material_crystallinity                           = true
material_final_print_temperature                 = 200                   # °C
material_initial_print_temperature               = 200                   # °C
material_keep_part_removal_temperature           = false
material_print_temperature                       = 200                   # °C
multiple_mesh_overlap                            = 0.10                  # mm
prime_tower_position_x                           = 275.5                 # mm
prime_tower_position_y                           = 255.5                 # mm
remove_empty_first_layers                        = true
retract_at_layer_change                          = true
retraction_amount                                = 1.5                   # mm
retraction_count_max                             = 45
retraction_speed                                 = 15                    # mm/s
skin_outline_count                               = 0
skin_preshrink                                   = 0                     # mm
skirt_gap                                        = 5                     # mm
skirt_line_count                                 = 3
speed_ironing                                    = 25                    # mm/s
speed_layer_0                                    = 20                    # mm/s
speed_print                                      = 40                    # mm/s
speed_print_layer_0                              = 20                    # mm/s
speed_slowdown_layers                            = 2
speed_support                                    = 40                    # mm/s
speed_support_interface                          = 40                    # mm/s
speed_topbottom                                  = 40                    # mm/s
speed_travel                                     = 170                   # mm/s
speed_travel_layer_0                             = 40                    # mm/s
speed_wall                                       = 40                    # mm/s
speed_wall_x                                     = 40                    # mm/s
speed_z_hop                                      = 10                    # mm/s
support_angle                                    = 60                    # °
support_bottom_enable                            = true
support_bottom_stair_step_height                 = 0.25                  # mm
support_bottom_stair_step_width                  = 3                     # mm
support_brim_width                               = 5                     # mm
support_infill_rate                              = 30                    # %
support_interface_density                        = 50                    # %
support_interface_enable                         = true
support_interface_height                         = 0.5                   # mm
support_interface_skip_height                    = 0.5                   # mm
support_join_distance                            = 5                     # mm
support_roof_enable                              = true
support_tower_maximum_supported_diameter         = 2                     # mm
support_use_towers                               = false
support_xy_distance                              = 0.625                 # mm
support_xy_distance_overhang                     = 0.625                 # mm
support_z_distance                               = 0.25                  # mm
support_zag_skip_count                           = 12
switch_extruder_retraction_speeds                = 15                    # mm/s
top_bottom_thickness                             = 1.0                   # mm
top_skin_expand_distance                         = 0                     # mm
top_skin_preshrink                               = 0                     # mm
travel_retract_before_outer_wall                 = true
wall_overhang_speed_factor                       = 80                    # %
wall_thickness                                   = 1                     # mm
wipe_retraction_amount                           = 2                     # mm
z_seam_x                                         = 141                   # mm
z_seam_y                                         = 141                   # mm

# Deleted settings:

#infill_line_width                                = 0.5                  # Inherits from line_width, which inherits from machine_nozzle_size
#raft_base_line_width                             = 0.5                  # Default is machine_nozzle_size * 2
#raft_airgap                                      = 0.3                  # Default is 0.3
#raft_interface_line_width                        = 0.5                  # Default is line_width * 2
#raft_surface_line_width                          = 0.5                  # Default is line_width
#raft_surface_line_spacing                        = 0.5                  # Default is raft_surface_line_width
#skin_line_width                                  = 0.5                  # Default is line_width
#roofing_line_width                               = 0.5                  # Default is skin_line_width
#skirt_brim_line_width                            = 0.5                  # Default is line_width
#support_interface_line_width                     = 0.5                  # Default is line_width
#support_roof_line_width                          = 0.5                  # Default is support_interface_line_width
#support_bottom_line_width                        = 0.5                  # Default support_interface_line_width
#support_line_width                               = 0.5                  # Default is line_width
#prime_tower_line_width                           = 0.5                  # Default is line_width
#wall_line_width                                  = 0.5                  # Default is line_width
#wall_line_width_0                                = 0.5                  # Default is wall_line_width
#wall_line_width_x                                = 0.5                  # Default is wall_line_width
#wireframe_height                                 = 3.8                  # Default is machine_nozzle_head_distance
#wireframe_roof_inset                             = 3.8                  # Default is wireframe_height
#support_roof_height                              = 0.5                  # Default is support_interface_height
#top_thickness                                    = 1.0                  # Default is top_bottom_thickness
#bottom_thickness                                 = 1.0                  # Default is top_bottom_thickness
#support_bottom_height                            = 0.5                  # Default is support_interface_height
#support_initial_layer_line_distance              = 1.6666666666666667   # Leave these as whatever the formulas are
#support_line_distance                            = 1.6666666666666667   # Leave these as whatever the formulas are
#min_skin_width_for_expansion                     = 6.123233995736766e-17 # Leave these as whatever the formulas are
#speed_support_roof                               = 40                    # Default is speed_support_interface
#speed_support_infill                             = 40                    # Default is speed_support
#speed_support_bottom                             = 40                    # Default is speed_support_interface
#sub_div_rad_add                                  = 0.5                   # Default is wall_line_width_x
#speed_wall_0                                     = 40                    # Default is speed_wall
#switch_extruder_retraction_speed                 = 15                    # Default is switch_extruder_retraction_speeds
#switch_extruder_prime_speed                      = 15                    # Default is switch_extruder_retraction_speeds
#wipe_retraction_speed                            = 15                    # Default is retraction_speed
#wipe_retraction_retract_speed                    = 15                    # Default is wipe_retraction_speed
#wipe_retraction_prime_speed                      = 15                    # Default is wipe_retraction_speed
#speed_prime_tower                                = 40                    # Default is speed_print
#skirt_brim_speed                                 = 20                    # Default is speed_layer_0
#infill_line_distance                             = 2                     # Use formula instead
#support_roof_line_distance                       = 1                     # Use formula instead
#support_bottom_line_distance                     = 1                     # Use formula instead
#support_roof_density                             = 50                    # Default is support_interface_density
#support_bottom_density                           = 50                    # Default is support_interface_density
#speed_roofing                                    = 40                    # Default is speed_topbottom
#retraction_retract_speed                         = 15                    # Default is wipe_retraction_speed
#retraction_prime_speed                           = 15                    # Default is retraction_speed
#material_bed_temperature_layer_0                 = 65                    # Default is material_bed_temperature
#material_print_temperature_layer_0               = 200                   # Default is material_print_temperature
#material_break_preparation_temperature           = 200                   # Default is material_print_temperature
#support_tree_collision_resolution                = 0.25                  # Default is support_line_width / 2
#support_top_distance                             = 0.25                  # Default is support_z_distance
#support_infill_sparse_thickness                  = 0.25                  # Default is layer_height
#infill_sparse_thickness                          = 0.25                  # Default is layer_height
#ironing_inset                                    = 0.25                  # Default is wall_line_width_0 / 2
#infill_wipe_dist                                 = 0.125                 # Default is wall_line_width_x / 4
#default_material_bed_temperature                 = 65                    # Use material_bed_temperature instead
#default_material_print_temperature               = 200                   # Use material_print_temperature instead
#cross_infill_pocket_size                         = 2                     # Default is infill_line_distance
#infill_overlap_mm                                = 0.05                  # Use formula instead
#retraction_extrusion_window                      = 1.5                   # Default retraction_amount
#travel_avoid_distance                            = 0.75                  # Default is machine_nozzle_tip_outer_diameter / 2 * 1.25
#wall_0_wipe_dist                                 = 0.125                 # Default is machine_nozzle_size / 2
#layer_0_z_overlap                                = 0                     # Raft setting, leave at default
#support_bottom_distance                          = 0.25                  # Default is support_z_distance
#top_layers                                       = 4                     # Default is top_thickness / resolveOrValue
#initial_bottom_layers                            = 4                     # Default is bottom_layers
#bottom_layers                                    = 4                     # Default is bottom_thickness / layer_height
#brim_line_count                                  = 10                    # Use formula
#support_brim_line_count                          = 10                    # Use formula
#retraction_min_travel                            = 1                     # Default is line_width * 2
#skin_overlap                                     = 5                     # Use formula
#skin_overlap_mm                                  = 0.025                 # Use formula
#speed_infill                                     = 40                    # Default is speed_print
#switch_extruder_retraction_amount                = 10                    # Default is machine_heat_zone_length