[metadata]

label = "TPU (shore hardness 95)"
date = "4/29/2020"

[settings]

acceleration_enabled                         = true
acceleration_infill                         = 800
acceleration_ironing                         = 800
acceleration_layer_0                         = 800
acceleration_prime_tower                         = 800
acceleration_print                         = 800
acceleration_print_layer_0                         = 800
acceleration_roofing                         = 800
acceleration_skirt_brim                         = 800
acceleration_support                         = 800
acceleration_support_bottom                         = 800
acceleration_support_infill                         = 800
acceleration_support_interface                         = 800
acceleration_support_roof                         = 800
acceleration_topbottom                         = 800
acceleration_travel                         = 800
acceleration_travel_layer_0                         = 800
acceleration_wall                         = 800
acceleration_wall_0                         = 800
acceleration_wall_x                         = 800
adhesion_type                         = "skirt"
connect_infill_polygons                         = true
connect_skin_polygons                         = true
cool_fan_full_at_height                         = 2.5
cool_min_layer_time                         = 15
cool_min_layer_time_fan_speed_max                         = 10
cool_min_speed                         = 10
infill_before_walls                         = false
infill_enable_travel_optimization                         = true
infill_pattern                         = "grid"
infill_randomize_start_location                         = true
infill_sparse_density                         = 25
infill_support_angle                         = 60
initial_bottom_layers                         = 2
ironing_inset                         = 0.25
ironing_line_spacing                         = 0.4
jerk_enabled                         = true
jerk_infill                         = 40
jerk_ironing                         = 40
jerk_layer_0                         = 40
jerk_prime_tower                         = 40
jerk_print                         = 40
jerk_print_layer_0                         = 40
jerk_roofing                         = 40
jerk_skirt_brim                         = 40
jerk_support                         = 40
jerk_support_bottom                         = 40
jerk_support_infill                         = 40
jerk_support_interface                         = 40
jerk_support_roof                         = 40
jerk_topbottom                         = 40
jerk_travel                         = 40
jerk_travel_layer_0                         = 40
jerk_wall                         = 40
jerk_wall_0                         = 40
jerk_wall_x                         = 40
layer_0_z_overlap                         = 0
layer_height                         = 0.25
layer_height_0                         = 0.25
limit_support_retractions                         = false
material_bed_temperature                         = 50
material_bed_temperature_layer_0                         = 55
material_final_print_temperature                         = 220
material_initial_print_temperature                         = 220
material_part_removal_temperature                         = 45
material_print_temperature                         = 230
material_print_temperature_layer_0                         = 220
retract_at_layer_change                         = true
retraction_amount                         = 1
retraction_count_max                         = 45
retraction_min_travel                         = 1
retraction_prime_speed                         = 20
retraction_retract_speed                         = 20
retraction_speed                         = 20
skirt_brim_speed                         = 15
skirt_gap                         = 5
skirt_line_count                         = 3
speed_infill                         = 35
speed_ironing                         = 15
speed_layer_0                         = 15
speed_prime_tower                         = 35
speed_print                         = 35
speed_print_layer_0                         = 15
speed_roofing                         = 35
speed_slowdown_layers                         = 3
speed_support                         = 35
speed_support_bottom                         = 35
speed_support_infill                         = 35
speed_support_interface	                         = 35
speed_support_roof                         = 35
speed_topbottom                         = 35
speed_travel                         = 160
speed_travel_layer_0                         = 50
speed_wall                         = 35
speed_wall_0                         = 35
speed_wall_x                         = 35
top_bottom_thickness                         = 1
travel_retract_before_outer_wall                         = true
z_seam_x                         = 141
z_seam_y                         = 141