# This file maps profile filenames (excluding .toml)
# to names as it appears in the UI drop down menus

[machine_profiles]
manufacturer = "ISB3DPRINTERS"
default_printer = "Cura Default"

[material_brands]
generic = "Unbranded"

[print_profiles]
default_filament = "Cura Default"
